CXX=g++
CXXFLAGS=-std=c++11

weird_algorithm: weird_algorithm.cpp
	$(CXX) $(CXXFLAGS) weird_algorithm.cpp -o ./builds/weird_algorithm

missing_number: missing_number.cpp
	$(CXX) $(CXXFLAGS) missing_number.cpp -o ./builds/missing_number
clean:
	rm ./builds/*
